### ISSUE TITLE
生成yolov5s.enine和deepsort.engine后，有边跟踪边检测的视频推理demo吗

### ISSUE THREAD

**Issue by WhXl** [RichardoMrMu/yolov5-deepsort-tensorrt#10]

**Comment by RichardoMrMu** [comment]
你可以遵循build and run部分，cmake make即可，记得把main.cpp中两个模型路径改成自己的。

**Comment by WhXl** [comment]
OK，谢谢，开源的项目很棒发自我的华为手机-------- 原始邮件 --------发件人： RichardoMrMu ***@***.***>日期： 2021年12月3日周五 傍晚6:43收件人： RichardoMrMu/yolov5-deepsort-tensorrt ***@***.***>抄送： WhXl ***@***.***>, Author ***@***.***>主    题： Re: [RichardoMrMu/yolov5-deepsort-tensorrt] 生成yolov5s.enine和deepsort.engine后，有边跟踪边检测的视频推理demo吗 (Issue #10)

你可以遵循build and run部分，cmake make即可，记得把main.cpp中两个模型路径改成自己的。
