### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 754467737** [RichardoMrMu/yolov5-deepsort-tensorrt#11]
-- Generating done
-- Build files have been written to: /home/mql/work/yolov5-deepsort-tensorrt-main/build
[ 64%] Built target deepsort
[ 70%] Building NVCC (Device) object CMakeFiles/yolov5_trt.dir/yolo/include/yolov5_trt_generated_yololayer.cu.o
nvcc fatal   : redefinition of argument 'std'
CMake Error at yolov5_trt_generated_yololayer.cu.o.Release.cmake:219 (message):
  Error generating
  /home/mql/work/yolov5-deepsort-tensorrt-main/build/CMakeFiles/yolov5_trt.dir/yolo/include/./yolov5_trt_generated_yololayer.cu.o

CMakeFiles/yolov5_trt.dir/build.make:326: recipe for target 'CMakeFiles/yolov5_trt.dir/yolo/include/yolov5_trt_generated_yololayer.cu.o' failed
make[2]: *** [CMakeFiles/yolov5_trt.dir/yolo/include/yolov5_trt_generated_yololayer.cu.o] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/yolov5_trt.dir/all' failed
make[1]: *** [CMakeFiles/yolov5_trt.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

make出现问题，不知道咋解决0-0

**Comment by RichardoMrMu** [comment]
请确定tensorrtx对应的yolov5版本是version5 而不是其他
