### ISSUE TITLE
c++代码中 很多new的变量最后没释放

### ISSUE THREAD

**Issue by jiujiangluck** [RichardoMrMu/yolov5-deepsort-tensorrt#12]
- DS
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/9ce6c5576bb2e4a41b9c90346d7883b418d27061/src/manager.cpp#L6-L13
- featureExtractor
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/9ce6c5576bb2e4a41b9c90346d7883b418d27061/deepsort/src/deepsort.cpp#L15-L27
- this->metric， this->kf
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/9ce6c5576bb2e4a41b9c90346d7883b418d27061/deepsort/src/tracker.cpp#L12-L27
- instance
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/9ce6c5576bb2e4a41b9c90346d7883b418d27061/deepsort/src/linear_assignment.cpp#L10-L14

**Comment by RichardoMrMu** [comment]
你可以给代码加上释放的逻辑
