### ISSUE TITLE
怎么使用yolov5-6.0

### ISSUE THREAD

**Issue by ScilenceForest** [RichardoMrMu/yolov5-deepsort-tensorrt#15]
我需要修改一些什么呢，6.0版本在结构上有一些调整，所以我也使用了最新的版本的tensorrtx并成功生成了engine文件（顺带一提，如果使用Yolov5-5.0，需要下载对应5.0的tensorrtx），但我不知道在代码里应该修改什么部分让它能成功运行6.0版本的yolov5。

**Comment by RichardoMrMu** [comment]
你可以尝试将yolo文件夹下的文件替换，编译运行

**Comment by shuya-cui** [comment]
> 

请问，您实现yolov5 6.0+deepsort了吗？具体是怎样修改的呢？

**Comment by ScilenceForest** [comment]
使用的yolov5 + opencv dnn模块读取.onnx + tensorRT读取deepsort的.engine




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RichardoMrMu/yolov5-deepsort-tensorrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月29日(星期二) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RichardoMrMu/yolov5-deepsort-tensorrt] 怎么使用yolov5-6.0 (Issue #15)





   
请问，您实现yolov5 6.0+deepsort了吗？具体是怎样修改的呢？

**Comment by mvpzhangqiu** [comment]
> 使用的yolov5 + opencv dnn模块读取.onnx + tensorRT读取deepsort的.engine
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "RichardoMrMu/yolov5-deepsort-tensorrt" ***@***.***&gt;; 发送时间:&nbsp;2022年3月29日(星期二) 晚上10:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [RichardoMrMu/yolov5-deepsort-tensorrt] 怎么使用yolov5-6.0 (Issue #15) 请问，您实现yolov5 6.0+deepsort了吗？具体是怎样修改的呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，请问这种方式您已经做成功了是吗？能不能给个repo参考一下
