### ISSUE TITLE
Deserialize the cuda engine failed.

### ISSUE THREAD

**Issue by liyanxi-0310** [RichardoMrMu/yolov5-deepsort-tensorrt#16]
你好，我是在win10下进行工程部署，成功编译后，将自己序列化生成的yolov5和deepsort的engine文件写到main.cpp中对应接口后，运行yolosort.exe时报错结果如下：
[E] [TRT] C:\source\rtSafe\coreReadArchive.cpp (58) - Serialization Error in nvinfer1::rt::CoreReadArchive::verifyHeader: 0 (Length in header does not match remaining archive length)。
想知道报错原因及解决办法，非常期待您的回复！

**Comment by RichardoMrMu** [comment]
请确定自己的tensorrtx版本是yolov5-v5版本的

**Comment by liyanxi-0310** [comment]
Yolo版本是确定的，我用的yolov5-5.0版本的tensorrtx进行的pt模型序列化得到yolov5.engine。
一开始我采用的网上下载的deepsort.engine和自己序列化的yolov5.engine进行yolosort.exe运行，报错如下：
[01/12/2022-09:53:37] [E] [TRT] C:\source\rtSafe\coreReadArchive.cpp (41) - Serialization Error in nvinfer1::rt::CoreReadArchive::verifyHeader: 0 (Version tag does not match. Note: Current Version: 96, Serialized Engine Version: 97)
[01/12/2022-09:53:37] [E] [TRT] INVALID_STATE: Unknown exception
[01/12/2022-09:53:37] [E] [TRT] INVALID_CONFIG: Deserialize the cuda engine failed.
上面这个问题**可能是因为下载的deepsort.engine生成版本和我电脑运行版本不匹配导致**，于是我通过用自己编译的onnx2engine.exe进行序列化生成的deepsort.engine 替换**解决了上述问题**，但是又报出了我最开始问的问题，所以不清楚该如何解决了，还请大佬指教具体！附：我目前的TensorRT是win10下的TensorRT 7.2.3.4 + CUDA10.2。
另外，大佬可否建立微信讨论群之类的供大家讨论，这样人多力量大，解决问题也会思路更多。

**Comment by justyk** [comment]
修改featuretensor.cpp 文件第66 行

std::ifstream engineStream(enginePath); 改为：std::ifstream engineStream(enginePath, std::ios::binary);

**Comment by liyanxi-0310** [comment]
> ```
> 	修改featuretensor.cpp 文件第66 行
> ```
> 
> std::ifstream engineStream(enginePath); 改为：std::ifstream engineStream(enginePath, std::ios::binary);

感谢！已解决！

**Comment by justyk** [comment]
您好~您发送的邮件我已收到~

**Comment by tuteming** [comment]
我在win10上跑
結果出現
yolov5_trt_create  ...
yolov5_trt_create  cuda engine...
yolov5_trt_create  buffer ...
yolov5_trt_create  stream ...
yolov5_trt_create  done ...
create yolov5-trt , instance = 000002B801D48290
delay_proress:6ms, delay_infer:2ms
delay_infer:13ms
delay_proress:7ms, delay_infer:2ms
delay_infer:13ms
delay_proress:1ms, delay_infer:2ms
...
這應該是都對的,但沒有opencv 的windows出來,請問我該加些甚麼?
謝謝

**Comment by RichardoMrMu** [comment]
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/src/manager.cpp#L32 将这一行的注释取消掉即可。
