### ISSUE TITLE
[question]How can I use this repository with my camera?

### ISSUE THREAD

**Issue by leeyunhome** [RichardoMrMu/yolov5-deepsort-tensorrt#21]
Hello, @RichardoMrMu 
Thanks for posting good stuff.

I am using a csi camera or usb camera like a pi camera.
How can I use this repository with my camera?
I want to test it with live video.

Thank you.
by neuezeal

**Comment by RichardoMrMu** [comment]
You can put your csi line like [this file](https://github.com/RichardoMrMu/yolov5-head-deepsort-detector/blob/d8316613324d53f0d3311218c7950435ffde0401/src/main.cpp)
