### ISSUE TITLE
运行yolosort时发生错误

### ISSUE THREAD

**Issue by 1997wzk** [RichardoMrMu/yolov5-deepsort-tensorrt#22]
在jetson nano上运行时
nano@nano-desktop:~/yolov5-deepsort-tensorrt-main/build$ ./yolosort
yolov5_trt_create  ...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by RichardoMrMu** [comment]
请确定使用的tensorrtx是yolov5-v5版本，tensorrt8.0和7.x有不少api的差别，所以如果想顺利尝试，可以使用tensort7.x

**Comment by 1997wzk** [comment]
@RichardoMrMu 谢谢，换成yolov5 5.0后可以运行yolosort,但是画面没有正常显示

**Comment by RichardoMrMu** [comment]
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/issues/25 请参考这个问题
