### ISSUE TITLE
運行的問題

### ISSUE THREAD

**Issue by tuteming** [RichardoMrMu/yolov5-deepsort-tensorrt#25]
我在win10上跑
char* yolo_engine = "d:/yolov5-deepsort-tensorrt_1/yolov5s.engine";
	char* sort_engine = "d:/yolov5-deepsort-tensorrt_1/deepsort.engine";
	float conf_thre = 0.4;
	Trtyolosort yosort(yolo_engine,sort_engine);
	VideoCapture capture;
	cv::Mat frame;
	//frame = capture.open("d:/yolov5-deepsort-tensorrt_1/test.mp4");
	frame = capture.open(0);
	if (!capture.isOpened()){
		std::cout<<"can not open"<<std::endl;
		return -1 ;
	}
	capture.read(frame);
結果出現
yolov5_trt_create ...
yolov5_trt_create cuda engine...
yolov5_trt_create buffer ...
yolov5_trt_create stream ...
yolov5_trt_create done ...
create yolov5-trt , instance = 000002B801D48290
delay_proress:6ms, delay_infer:2ms
delay_infer:13ms
delay_proress:7ms, delay_infer:2ms
delay_infer:13ms
delay_proress:1ms, delay_infer:2ms
...
這應該是都對的,但沒有opencv 的windows出來,請問我該加些甚麼?
謝謝

**Comment by RichardoMrMu** [comment]
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/src/manager.cpp#L14，请参考showdetection，你想看检测的结果，需要将图片show出来即可。

**Comment by tuteming** [comment]
以解決  謝謝

**Comment by 1997wzk** [comment]
@tuteming 我遇到了相同的问题，请问您是怎样解决的？

**Comment by tiedaneri** [comment]
> @tuteming 我遇到了相同的问题，请问您是怎样解决的？

将manager.cpp中TrtDetect函数中调用的showDetection函数注释打开
