### ISSUE TITLE
ref.

### ISSUE THREAD

**Issue by tuteming** [RichardoMrMu/yolov5-deepsort-tensorrt#31]
DeepSORT C++版的一个bug
https://blog.csdn.net/XCCCCZ/article/details/121877072
please ref.
that is right or wrong?

thanks

**Comment by RichardoMrMu** [comment]
Maybe that is right, you can change it and test it.

**Comment by ggyybb** [comment]
> 

博客应该是对的，你改了测试了么

**Comment by RichardoMrMu** [comment]
你可以自己修改测试。
