### ISSUE TITLE
未检测成功+请问如何更改跟踪目标

### ISSUE THREAD

**Issue by adudoctor** [RichardoMrMu/yolov5-deepsort-tensorrt#34]
1.运行后未能检测人群，只检测到车辆，结果如图
![屏幕截图 2022-03-26 171015](https://user-images.githubusercontent.com/102410266/160232919-f449552a-b341-4dc9-83a5-a3d58399b55b.jpg)

2.请问如何更改跟踪目标，如只跟踪车辆，只跟踪人物

**Comment by RichardoMrMu** [comment]
你可以选择跟踪的类别对模型进行训练，如训练只检测人的模型。

**Comment by adudoctor** [comment]
> 你可以选择跟踪的类别对模型进行训练，如训练只检测人的模型。

我用的是官方yolov5.pt，请问我的图片只检测到车没有检测到人呢？

**Comment by RichardoMrMu** [comment]
请确定yolo模型检测是否正常

**Comment by adudoctor** [comment]
> 请确定yolo模型检测是否正常

是正常的，这是我执行命令./yolov5 -d yolov5s.engine ../samples命令得到的图片
![_bus](https://user-images.githubusercontent.com/102410266/160235893-d2db10a1-95a7-4a3d-9c8b-93dd4d0768eb.jpg)

**Comment by adudoctor** [comment]
我在manager.cpp第31行DS->sort(frame,det)前的showDetection(frame,det)能看出yolov5成功检测出目标，如图
![屏幕截图 2022-03-26 192500](https://user-images.githubusercontent.com/102410266/160237266-48f45a05-9128-442f-bb26-f2e67b2174a8.jpg)

但在manager.cpp第31行DS->sort(frame,det)后的showDetection(frame,det)不再显示行人bounding box，说明det发生变化，
![屏幕截图 2022-03-26 171015](https://user-images.githubusercontent.com/102410266/160237332-0f734c73-9e8d-4108-88b1-e0a850d41155.jpg)

**Comment by adudoctor** [comment]
请问manager.cpp第31行DS->sort(frame,det);做了什么导致行人的bounding box信息消失了

**Comment by RichardoMrMu** [comment]
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/deepsort/include/tracker.h#L30
https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/deepsort/include/tracker.h#L31
你可以尝试修改这两行为
```c++
float max_iou_distance = 0.7,
int max_age = 70, int n_init=3
```

**Comment by adudoctor** [comment]
> https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/deepsort/include/tracker.h#L30
> 
> 
> https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/deepsort/include/tracker.h#L31
> 
> 
> 你可以尝试修改这两行为
> ```c++
> float max_iou_distance = 0.7,
> int max_age = 70, int n_init=3
> ```

非常感谢！行人的bounding box显示出来了

**Comment by shuya-cui** [comment]
> > https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/deepsort/include/tracker.h#L30
> > 
> > https://github.com/RichardoMrMu/yolov5-deepsort-tensorrt/blob/985e83196fb2d84f814f35518b2f9b30ceb64ea0/deepsort/include/tracker.h#L31
> > 
> > 你可以尝试修改这两行为
> > ```c++
> > float max_iou_distance = 0.7,
> > int max_age = 70, int n_init=3
> > ```
> 
> 非常感谢！行人的bounding box显示出来了

请问这两个参数是指什么？
