### ISSUE TITLE
测试长视频时，deepsort_tet会一直申请内存导致内存爆掉

### ISSUE THREAD

**Issue by ChaiYuanYuan-bit** [RichardoMrMu/yolov5-deepsort-tensorrt#37]
运行正常的时候：
vector: 24
origin img size:960 540
yolov5_trt_detect start preprocess img
after preprocess_img pr_img size:640 640
after preprocess_img frame size:960 540
yolov5_trt_detect start convert img to float
yolov5_trt_detect start do inference
![image](https://user-images.githubusercontent.com/59736008/164892729-cd55e679-317f-46a2-bd95-fecf4410e601.png)

运行一段时间后，当显存被占满时，deepsort直接停止工作，框会一直停留在那一帧，但是yolo还在继续跑：
CUDA error 2 at F:\Detections\yolov5-deepsort-tensorrt\yolo\src\yolov5_lib.cpp:30[04/23/2022-18:43:35] [E] [TRT] C:\source\rtSafe\safeContext.cpp (133) - Cudnn Error in nvinfer1::rt::CommonContext::configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
[04/23/2022-18:43:35] [E] [TRT] FAILED_EXECUTION: Unknown exception

![image](https://user-images.githubusercontent.com/59736008/164892773-4d540576-0fef-4f3e-95ad-2ce6e9287946.png)

我的配置：
GTX1050ti-Notebook 4GB
CUDAA10.1
cudnn-10.1-windows10-x64-v7.6.5.32
NVIDIA Drive 497.33
opencv-3.3-vc14
cmake-3.17.1-windows-x86_64
TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.0.cudnn7.6

**Comment by guishilike** [comment]
这个问题解决了吗
