### ISSUE TITLE
Deserialize the cuda engine failed.

### ISSUE THREAD

**Issue by likehengqq** [RichardoMrMu/yolov5-deepsort-tensorrt#5]
when i run the command line of  ./demo ../resource/deepsort.engine ../resources/track.txt
but, show below
[10/31/2021-21:09:01] [E] [TRT] INVALID_ARGUMENT: Cannot deserialize with an empty memory buffer.
[10/31/2021-21:09:01] [E] [TRT] INVALID_CONFIG: Deserialize the cuda engine failed.
Segmentation fault (core dumped)

**Comment by RichardoMrMu** [comment]
which version is your tensorrt and did you generator the deepsort engine file correctly?

**Comment by likehengqq** [comment]
Thank you，The problem has been solved.

**Comment by Mrgao9** [comment]
> when i run the command line of ./demo ../resource/deepsort.engine ../resources/track.txt but, show below [10/31/2021-21:09:01] [E] [TRT] INVALID_ARGUMENT: Cannot deserialize with an empty memory buffer. [10/31/2021-21:09:01] [E] [TRT] INVALID_CONFIG: Deserialize the cuda engine failed. Segmentation fault (core dumped)

@likehengqq Hello, I have the same problem. How did you solve it?

**Comment by Mrgao9** [comment]
> > when i run the command line of ./demo ../resource/deepsort.engine ../resources/track.txt but, show below [10/31/2021-21:09:01] [E] [TRT] INVALID_ARGUMENT: Cannot deserialize with an empty memory buffer. [10/31/2021-21:09:01] [E] [TRT] INVALID_CONFIG: Deserialize the cuda engine failed. Segmentation fault (core dumped)
> 
> @likehengqq Hello, I have the same problem. How did you solve it?

@likehengqq 非常期望您能回复，非常感谢！

**Comment by RichardoMrMu** [comment]
我知道了原因，运行./demo ../resource/deepsort.engine ../resources/track.txt请在图形化界面下运行，在命令行下，因为gui没法出现，所以会报错

**Comment by SherlockMoriaty** [comment]
> Thank you，The problem has been solved.
I have the same probelm. I would appreciate it if you could introduce the details about how you solved it.

**Comment by SherlockMoriaty** [comment]
> Thank you，The problem has been solved.

I have the same probelm. I would appreciate it if you could introduce the details about how you solved it.

**Comment by RichardoMrMu** [comment]
Please ensure run the comand in graphical interface.

**Comment by blain-s** [comment]
I am having the same issue, was the reason for this error ever discovered?
