### ISSUE TITLE
[WARNING]::Batch size overflow, input will be truncated!

### ISSUE THREAD

**Issue by MrRangerss** [RichardoMrMu/yolov5-deepsort-tensorrt#6]
Hi, when I test the program using my own data, I meet one question that the output shows that the batch size is overflow, so I wonder whether can I change the imgShape to solve that problem?  And how can I tune that parameter? The value of imgShape in deepsort.cpp is cv::Size(64, 128), and I don't know why the value is (64, 128), can you help me?

**Comment by MrRangerss** [comment]
Sorry, it's my fault. I know what's wrong

**Comment by huangqi111** [comment]
Batch size overflow, input will be truncated!,I also encountered this problem  how you solved it over there？
