### ISSUE TITLE
.onnx2engine ../resources/deepsort.onnx ../resources/deepsort.engine

### ISSUE THREAD

**Issue by YangChen-UCAS** [RichardoMrMu/yolov5-deepsort-tensorrt#9]
when I run .onnx2engine ../resources/deepsort.onnx ../resources/deepsort.engine, I meet an error that .onnx2engine:command not found, deer Mu ,do you know how to solve this error?

**Comment by RichardoMrMu** [comment]
I am sorry, I write wrong. It should be 
```shell
./onnx2engine ../resources/deepsort.onnx ../resources/deepsort.engine
```

**Comment by YangChen-UCAS** [comment]
thank you for your excellent job, I have done all the steps you mentioned in this github project. but I don't know how to use the  yolov5s.engine and deepsort.engine together for multi-object tracking?

**Comment by RichardoMrMu** [comment]
Just follow Build and Run. you need cmake and make the project. And remember to change path in majn.cpp as your own yolo and deepsort model path .
